#!/bin/bash

# Run Gnome daemons
gnome-screensaver &
gnome-settings-daemon &
gnome-power-manager &
sleep 2

# Run trayer to host applications that uses the traybar (e.g., Skype)
trayer --edge top --align right --widthtype pixel --width 100 --height 17 --tint 0x3f3f3f --transparent true --alpha 0 &

# NetMonitor applet for managing wireless connections
nm-applet &

# Fire up Xmonad
exec xmonad
